### PR TITLE
Create colored svg in c++ code.

### PR DESCRIPTION
**Pull request by sylmroz**
- Create colored svg in c++ code. Basically it is simillar algoritm from repo https://github.com/tomayac/SVGcode
The porpouse was to speedup colored svg by using c++ code. 
- Create building scripts for windows platform
- Use em++ compiler to use c++ language

### CODE REVIEW

**Comment by tomayac** [comment]
Wow, this looks amazing. Thanks `<3` so much for contributing this improvement! I’ll review this after the weekend and merge it hopefully on Monday!

**Comment by tomayac** [comment]
Addendum: since your build script also appends the `export` manually, I wonder if you manage to get the proper way of doing this via `-s "MODULARIZE=1" -s "EXPORT_ES6=1"` to work? See my poor attempt in #1, which fails. I have no idea what I’m doing when it comes to emscripten (and C or C++), but you are obviously a master of both. Maybe you succeed in outputting a proper ES module directly from emscripten?

**Comment by sylmroz** [comment]
Thanks! That sounds great. :) Could You first check does it not cause any problems with Your existing SVG code? If Yes I will fix it asap.

I guess it is not as simple as we think to just modularize. I think, following documentation and examples from StackOverflow it seems like a modularization creates a module that needs to be instantiated and used like is in src/potrace.js file.
The potrace.js shouldn't be bundled into one module because it just hides the required implementation. You can see that in index.js file when You will use -gsource-map flag in the build script.
Following that example https://github.com/imxood/emcc-typescript-example and that one https://github.com/emscripten-core/emscripten/issues/10271 I see that it can be done also combining with a typescript.
I can do that in the next PR when I find a time next weekend. It will be much more code refactoring but seems reasonable to change it. Now in my typescript project, I need to define my own types which is annoying :)

**Comment by tomayac** [comment]
I have played a bit with this, but fail to get _super_ convincing results:

## Your PR:

- Quant level 1:
  Screen Shot 2022-01-31 at 13 50 23
- Quant level 75 (I don't understand the "flipping over" of colors as in the second example.):
    Screen Shot 2022-01-31 at 13 51 30
- Quant level 100:
    Screen Shot 2022-01-31 at 13 51 00

## Current client-side implementation:

The current SVGcode output with the default settings is this:

Screen Shot 2022-01-31 at 13 53 30

## Posterization in SVGcode

When you paste `$('label[hidden]').hidden = false` into the DevTools console, you can toggle debug mode:

Screen Shot 2022-01-31 at 14 02 55

This allows you to see what the app is doing internally (top: input image, bottom: [posterized](https://en.wikipedia.org/wiki/Posterization) input image):

Screen Shot 2022-01-31 at 14 03 26

Posterization happens on all four channels (r, g, b, a) independently, essentially as in this [CodePen demo](https://codepen.io/AmeliaBR/pen/ZYGYOQ). 

Do the results of the demo look entirely different for you? Maybe it's a problem on my side?

**Comment by sylmroz** [comment]
Thanks for the tests!
Yeah, I made one mistake in code. It should be fixed now. In c++ You must be careful about variables size :)
Your algorithm works fine.

The best results (visual and speed) I get now when I used canvas with posterization filter  - from Your code - and quant level = 255 so it means - no quantization, and results I pushed to the c++ code. It just needs 55ms on my machine to generate that result:
image
which looks really similar to your result.

Without posterization and quant level = 5 I get that result:
image
Which is close to the original

**Comment by sylmroz** [comment]
And to get that black color You need to use
```A snail.``` indstead of div. As a backgroundis white.

**Comment by sylmroz** [comment]
Now quant level has the same behavior as the step value from SVGcode, but it is one value for all channels. The value should be between <1;255>

**Comment by sylmroz** [comment]
I added a swith to choose between simple ( 0 ) and interpolated ( 1 ) posterization
First is faster but second has beetter results.
image

**Comment by tomayac** [comment]
I cannot really reproduce the results from your screenshots. If I run the following code from the demo, I get the image below, which has a lot more white holes than your screenshots:

```js
potrace(blob, {
    turdsize: 2,
    turnpolicy: 4,
    alphamax: 1,
    opticurve: 1,
    opttolerance: 0.2,
    pathonly: false,
    extractColors: true,
    posterizeLevel: 6,
    posterizationAlgorithm: 0, // 0 - simple, 1 - interpolation
}
```

Screen Shot 2022-02-01 at 13 51 11

A couple of review remarks:

- Potrace exposes all settings as lower case, please do so as well for consistency: `posterizationAlgorithm` → `posterizationalgorithm` for all parameters.
- What do you want to expose: `quantlevel` or `posterizelevel`? So far the code uses both. 

A meta level remark: 

- Maybe you want to contribute these changes upstream to the core [Potrace project](http://potrace.sourceforge.net/) and we can then work here on creating a Wasm version of that? Sorry, I realized this only a bit late, but it would actually make more sense directly upstream.

**Comment by tomayac** [comment]
Thank you very much for this contribution! `<3`

**Pull request merged**
